-- MySQL Script generated by MySQL Workbench
-- Tue Sep 26 22:30:45 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema language_center_management
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema language_center_management
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `language_center_management` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `language_center_management` ;

-- -----------------------------------------------------
-- Table `language_center_management`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `language_center_management`.`account` (
  `account_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(150) NOT NULL,
  `password` VARCHAR(1000) NOT NULL,
  `fullname` VARCHAR(1000) NULL DEFAULT NULL,
  `role_id` INT NULL DEFAULT NULL,
  `gender` BIT(1) NULL DEFAULT NULL,
  `dob` DATE NULL DEFAULT NULL,
  `address` VARCHAR(1000) NULL DEFAULT NULL,
  `phone` VARCHAR(10) NULL DEFAULT NULL,
  `image` VARCHAR(1000) NULL DEFAULT NULL,
  `email` VARCHAR(1000) NULL DEFAULT NULL,
  `amount` FLOAT NULL DEFAULT NULL,
  `desc` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`account_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `language_center_management`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `language_center_management`.`department` (
  `department_id` INT AUTO_INCREMENT  NOT NULL,
  `department_name` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`department_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `language_center_management`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `language_center_management`.`comment` (
  `comment_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(150) NULL DEFAULT NULL,
  `content` VARCHAR(1000) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `department_id` INT NOT NULL,
  `account_id` INT NOT NULL,
  `lesson_id` INT NOT NULL,
  `status` BIT(1) NOT NULL,
  PRIMARY KEY (`comment_id`),
  INDEX `fk_Comment_department1_idx` (`department_id` ASC) VISIBLE,
  INDEX `fk_Comment_account1_idx` (`account_id` ASC) VISIBLE,
  INDEX `fk_Comment_lesson1_idx` (`lesson_id` ASC) VISIBLE,
  CONSTRAINT `fk_Comment_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `language_center_management`.`account` (`account_id`),
  CONSTRAINT `fk_Comment_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `language_center_management`.`department` (`department_id`),
  CONSTRAINT `fk_Comment_lesson1`
    FOREIGN KEY (`lesson_id`)
    REFERENCES `language_center_management`.`lesson` (`lesson_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `language_center_management`.`lecture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `language_center_management`.`lecture` (
  `lecture_id` INT NOT NULL AUTO_INCREMENT,
  `lecture_name` VARCHAR(1000) NOT NULL,
  `course_id` INT NULL DEFAULT NULL,
  `create_at` DATE NULL DEFAULT NULL,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  `status` BIT(1) NOT NULL,
  PRIMARY KEY (`lecture_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `language_center_management`.`lesson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `language_center_management`.`lesson` (
  `lesson_id` INT AUTO_INCREMENT NOT NULL,
  `lesson_name` VARCHAR(1000) NOT NULL,
  `video` VARCHAR(1000) NOT NULL,
  `main` TEXT NULL DEFAULT NULL,
  `lecture_id` INT NULL DEFAULT NULL,
  `update_at` DATE NULL DEFAULT NULL,
  `status` BIT(1) NOT NULL,
  PRIMARY KEY (`lesson_id`),
  INDEX `fk_Lesson_Lecture1_idx` (`lecture_id` ASC) VISIBLE,
  CONSTRAINT `fk_Lesson_Lecture1`
    FOREIGN KEY (`lecture_id`)
    REFERENCES `language_center_management`.`lecture` (`lecture_id`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `language_center_management`.`homework`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `language_center_management`.`homework` (
  `homework_id` INT NOT NULL,
  `content` VARCHAR(1000) NULL DEFAULT NULL,
  `lesson_id` INT NOT NULL,
  PRIMARY KEY (`homework_id`),
  INDEX `fk_Homework_lesson1_idx` (`lesson_id` ASC) VISIBLE,
  CONSTRAINT `fk_Homework_lesson1`
    FOREIGN KEY (`lesson_id`)
    REFERENCES `language_center_management`.`lesson` (`lesson_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `language_center_management`.`account_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `language_center_management`.`account_comment` (
  `lesson_id` INT NOT NULL,
  `account_id` INT NOT NULL,
  `comment_id` INT NOT NULL,
  `homework_id` INT NOT NULL,
  INDEX `fk_account_comment_lesson1_idx` (`lesson_id` ASC) VISIBLE,
  INDEX `fk_account_comment_account1_idx` (`account_id` ASC) VISIBLE,
  INDEX `fk_account_comment_Comment1_idx` (`comment_id` ASC) VISIBLE,
  INDEX `fk_account_comment_Homework1` (`homework_id` ASC) VISIBLE,
  CONSTRAINT `fk_account_comment_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `language_center_management`.`account` (`account_id`),
  CONSTRAINT `fk_account_comment_Comment1`
    FOREIGN KEY (`comment_id`)
    REFERENCES `language_center_management`.`comment` (`comment_id`),
  CONSTRAINT `fk_account_comment_Homework1`
    FOREIGN KEY (`homework_id`)
    REFERENCES `language_center_management`.`homework` (`homework_id`),
  CONSTRAINT `fk_account_comment_lesson1`
    FOREIGN KEY (`lesson_id`)
    REFERENCES `language_center_management`.`lesson` (`lesson_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `language_center_management`.`level`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `language_center_management`.`level` (
  `level_id` INT NOT NULL,
  `level` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`level_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `language_center_management`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `language_center_management`.`course` (
  `course_id` INT AUTO_INCREMENT NOT NULL,
  `course_name` VARCHAR(1000) NOT NULL,
  `price` FLOAT NOT NULL,
  `image` VARCHAR(1000) NULL DEFAULT NULL,
  `language` VARCHAR(1000) NULL DEFAULT NULL,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  `is_sale` INT NULL DEFAULT NULL,
  `update_at` DATE NOT NULL,
  `department_id` INT NOT NULL,
  `account_id` INT NULL DEFAULT NULL,
  `level_id` INT NOT NULL,
  `status` BIT(1) NOT NULL,
  PRIMARY KEY (`course_id`),
  INDEX `fk_Course_Department1_idx` (`department_id` ASC) VISIBLE,
  INDEX `fk_Course_Account1_idx` (`account_id` ASC) VISIBLE,
  INDEX `fk_Course_Level1_idx` (`level_id` ASC) VISIBLE,
  CONSTRAINT `fk_Course_Account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `language_center_management`.`account` (`account_id`),
  CONSTRAINT `fk_Course_Department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `language_center_management`.`department` (`department_id`),
  CONSTRAINT `fk_Course_Level1`
    FOREIGN KEY (`level_id`)
    REFERENCES `language_center_management`.`level` (`level_id`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `language_center_management`.`account_course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `language_center_management`.`account_course` (
  `account_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  PRIMARY KEY (`account_id`, `course_id`),
  INDEX `fk_Account_course_Account1_idx` (`account_id` ASC) VISIBLE,
  INDEX `fk_Account_course_Course1` (`course_id` ASC) VISIBLE,
  CONSTRAINT `fk_Account_course_Account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `language_center_management`.`account` (`account_id`),
  CONSTRAINT `fk_Account_course_Course1`
    FOREIGN KEY (`course_id`)
    REFERENCES `language_center_management`.`course` (`course_id`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `language_center_management`.`account_lesson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `language_center_management`.`account_lesson` (
  `course_id` INT NOT NULL,
  `account_id` INT NOT NULL,
  `lesson_id` INT NOT NULL,
  INDEX `fk_Account_lesson_Account1_idx` (`account_id` ASC) VISIBLE,
  INDEX `fk_Account_lesson_Lesson1_idx` (`lesson_id` ASC) VISIBLE,
  INDEX `fk_Account_lesson_Course1` (`course_id` ASC) VISIBLE,
  CONSTRAINT `fk_Account_lesson_Account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `language_center_management`.`account` (`account_id`),
  CONSTRAINT `fk_Account_lesson_Course1`
    FOREIGN KEY (`course_id`)
    REFERENCES `language_center_management`.`course` (`course_id`),
  CONSTRAINT `fk_Account_lesson_Lesson1`
    FOREIGN KEY (`lesson_id`)
    REFERENCES `language_center_management`.`lesson` (`lesson_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `language_center_management`.`attendance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `language_center_management`.`attendance` (
  `attendance_id` INT NOT NULL,
  `Is_attendance` BIT(1) NOT NULL,
  `lesson_id` INT NOT NULL,
  `account_id` INT NOT NULL,
  PRIMARY KEY (`attendance_id`),
  INDEX `fk_Attendance_lesson1_idx` (`lesson_id` ASC) VISIBLE,
  INDEX `fk_Attendance_account1_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_Attendance_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `language_center_management`.`account` (`account_id`),
  CONSTRAINT `fk_Attendance_lesson1`
    FOREIGN KEY (`lesson_id`)
    REFERENCES `language_center_management`.`lesson` (`lesson_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `language_center_management`.`exam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `language_center_management`.`exam` (
  `exam_id` INT NOT NULL,
  `exam_name` VARCHAR(1000) NOT NULL,
  `quantity` INT NOT NULL,
  `time` INT NOT NULL,
  `start_date` DATE NOT NULL,
  `lecture_id` INT NOT NULL,
  PRIMARY KEY (`exam_id`),
  INDEX `fk_Exam_Lecture1_idx` (`lecture_id` ASC) VISIBLE,
  CONSTRAINT `fk_Exam_Lecture1`
    FOREIGN KEY (`lecture_id`)
    REFERENCES `language_center_management`.`lecture` (`lecture_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `language_center_management`.`feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `language_center_management`.`feedback` (
  `feedback_id` INT AUTO_INCREMENT NOT NULL,
  `message` VARCHAR(1000) NULL DEFAULT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `comment_id` INT NOT NULL,
  `status` BIT(1) NOT NULL,
  PRIMARY KEY (`feedback_id`),
  INDEX `fk_Feedback_Blog1_idx` (`comment_id` ASC) VISIBLE,
  CONSTRAINT `fk_Feedback_comment1`
    FOREIGN KEY (`comment_id`)
    REFERENCES `language_center_management`.`comment` (`comment_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `language_center_management`.`feedback_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `language_center_management`.`feedback_account` (
  `account_id` INT NOT NULL,
  `feedback_id` INT NOT NULL,
  INDEX `fk_Feedback_account_Account1_idx` (`account_id` ASC) VISIBLE,
  INDEX `fk_Feedback_account_Feedback1_idx` (`feedback_id` ASC) VISIBLE,
  CONSTRAINT `fk_Feedback_account_Account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `language_center_management`.`account` (`account_id`),
  CONSTRAINT `fk_Feedback_account_Feedback1`
    FOREIGN KEY (`feedback_id`)
    REFERENCES `language_center_management`.`feedback` (`feedback_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `language_center_management`.`lecture_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `language_center_management`.`lecture_account` (
  `account_id` INT NOT NULL,
  `lecture_id` INT NOT NULL,
  PRIMARY KEY (`account_id`, `lecture_id`),
  INDEX `fk_Lecture_account_Account1_idx` (`account_id` ASC) VISIBLE,
  INDEX `fk_Lecture_account_Lecture1_idx` (`lecture_id` ASC) VISIBLE,
  CONSTRAINT `fk_Lecture_account_Account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `language_center_management`.`account` (`account_id`),
  CONSTRAINT `fk_Lecture_account_Lecture1`
    FOREIGN KEY (`lecture_id`)
    REFERENCES `language_center_management`.`lecture` (`lecture_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `language_center_management`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `language_center_management`.`order` (
  `order_id` INT NOT NULL,
  `order_date` DATE NULL DEFAULT NULL,
  `total_price` FLOAT NULL DEFAULT NULL,
  `account_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_Order_Account1_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_Order_Account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `language_center_management`.`account` (`account_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `language_center_management`.`order_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `language_center_management`.`order_detail` (
  `orderDetail_id` INT NOT NULL,
  `quantity` INT NULL DEFAULT NULL,
  `course_id` INT NULL DEFAULT NULL,
  `order_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`orderDetail_id`),
  INDEX `fk_Order_detail_Course1_idx` (`course_id` ASC) VISIBLE,
  INDEX `fk_Order_detail_Order1_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_Order_detail_Course1`
    FOREIGN KEY (`course_id`)
    REFERENCES `language_center_management`.`course` (`course_id`),
  CONSTRAINT `fk_Order_detail_Order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `language_center_management`.`order` (`order_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `language_center_management`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `language_center_management`.`question` (
  `question_id` INT NOT NULL,
  `quiz` VARCHAR(1000) CHARACTER SET 'utf8mb3' NOT NULL,
  `op1` VARCHAR(1000) CHARACTER SET 'utf8mb3' NOT NULL,
  `op2` VARCHAR(1000) CHARACTER SET 'utf8mb3' NOT NULL,
  `op3` VARCHAR(1000) CHARACTER SET 'utf8mb3' NOT NULL,
  `op4` VARCHAR(1000) CHARACTER SET 'utf8mb3' NOT NULL,
  `solution` VARCHAR(4) NOT NULL,
  `lecture_id` INT NOT NULL,
  PRIMARY KEY (`question_id`),
  INDEX `fk_Question_Lecture1_idx` (`lecture_id` ASC) VISIBLE,
  CONSTRAINT `fk_Question_Lecture1`
    FOREIGN KEY (`lecture_id`)
    REFERENCES `language_center_management`.`lecture` (`lecture_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `language_center_management`.`result`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `language_center_management`.`result` (
  `result_id` INT NOT NULL,
  `score` FLOAT NULL DEFAULT NULL,
  `correctAnswer` INT NOT NULL,
  `status` VARCHAR(150) NOT NULL,
  `time` VARCHAR(45) NOT NULL,
  `Resultcol` INT NOT NULL,
  `account_id` INT NULL DEFAULT NULL,
  `exam_id` INT NOT NULL,
  PRIMARY KEY (`result_id`),
  INDEX `fk_Result_Account1_idx` (`account_id` ASC) VISIBLE,
  INDEX `fk_Result_Exam1_idx` (`exam_id` ASC) VISIBLE,
  CONSTRAINT `fk_Result_Account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `language_center_management`.`account` (`account_id`),
  CONSTRAINT `fk_Result_Exam1`
    FOREIGN KEY (`exam_id`)
    REFERENCES `language_center_management`.`exam` (`exam_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `language_center_management`.`wishlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `language_center_management`.`wishlist` (
  `account_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  INDEX `fk_Wishlist_Account1_idx` (`account_id` ASC) VISIBLE,
  INDEX `fk_Wishlist_Course1_idx` (`course_id` ASC) VISIBLE,
  CONSTRAINT `fk_Wishlist_Account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `language_center_management`.`account` (`account_id`),
  CONSTRAINT `fk_Wishlist_Course1`
    FOREIGN KEY (`course_id`)
    REFERENCES `language_center_management`.`course` (`course_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `language_center_management`.`Notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `language_center_management`.`notification` (
  `notification_id` INT NOT NULL,
  `account_id` INT NOT NULL,
  `message` VARCHAR(1000) NULL,
  PRIMARY KEY (`notification_id`),
  INDEX `fk_Notification_account1_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_Notification_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `language_center_management`.`account` (`account_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `language_center_management`.`user_comment_responses` (
  `response_id` INT NOT NULL AUTO_INCREMENT,
  `comment_id` INT NOT NULL,
  `account_id` INT NOT NULL,
  `response_content` VARCHAR(1000) NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `status` BIT(1) NOT NULL,
  PRIMARY KEY (`response_id`, `account_id`),
  INDEX `fk_User_Comment_Responses_Comment1_idx` (`comment_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_Comment_Responses_Comment1`
    FOREIGN KEY (`comment_id`)
    REFERENCES `language_center_management`.`comment` (`comment_id`),
  CONSTRAINT `fk_User_Comment_Responses_Account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `language_center_management`.`account` (`account_id`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
